#!/bin/sh
### BEGIN INIT INFO
# Provides:          td-agent
# Required-Start:    $network $local_fs
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: data collector for Treasure Data
# Description:       Treasure Data Support <support@treasure-data.com>
### END INIT INFO

# Author: Kazuki Ohta <k@treasure-data.com>

# Introduce the short server's name here
NAME=td-agent

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
USER=td-agent                   # Running user
GROUP=td-agent                  # Running group
DESC=td-agent                   # Introduce a short description here
PIDFILE=/var/run/$NAME/$NAME.pid
DAEMON=/usr/lib/fluent/ruby/bin/ruby # Introduce the server's location here
# Arguments to run the daemon with
TD_AGENT_CMD="/usr/sbin/td-agent"
DAEMON_ARGS="$TD_AGENT_CMD $DAEMON_ARGS --daemon $PIDFILE --log /var/log/td-agent/td-agent.log"
SCRIPTNAME=/etc/init.d/$NAME
START_STOP_DAEMON_ARGS=""

# Exit if the package is not installed
[ -x $DAEMON ] || exit 0

# Load the VERBOSE setting and other rcS variables
# . /lib/init/vars.sh
VERBOSE="yes"

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.0-6) to ensure that this file is present.
. /lib/lsb/init-functions

# Check the user
if [ -n "${USER}" ]; then
	if ! getent passwd | grep -q "^${USER}:"; then
		echo "$0: user for running td-agent doesn't exist: ${USER}" >&2
		exit 1
	fi
	if [ ! -d $(dirname ${PIDFILE}) ]; then
		mkdir -p $(dirname ${PIDFILE})
	fi
	chown -R ${USER} $(dirname ${PIDFILE})
	START_STOP_DAEMON_ARGS="${START_STOP_DAEMON_ARGS} -c ${USER}"
fi
if [ -n "${GROUP}" ]; then
	if ! getent group | grep -q "^${GROUP}:"; then
		echo "$0: group for running td-agent doesn't exist: ${GROUP}" >&2
		exit 1
	fi
	START_STOP_DAEMON_ARGS="${START_STOP_DAEMON_ARGS} --group ${GROUP}"
fi

# 2012/04/17 Kazuki Ohta <k@treasure-data.com>
# Use jemalloc to avoid memory fragmentation
if [ -f "/usr/lib/fluent/jemalloc/lib/libjemalloc.so" ]; then
	export LD_PRELOAD=/usr/lib/fluent/jemalloc/lib/libjemalloc.so
fi

get_pids()
{
	 pgrep -f "^$DAEMON $TD_AGENT_CMD"
}

# Usage: wait_pids TIMEOUT
# Every second wait_pids checks if get_pids returns any PIDs and:
#   - Returns 0 if no get_pids does not return any PIDs anymore
#   - Returns 2 if TIMEOUT is reached
wait_pids()
{
	 retval=0
	 counter=0
	 timeout=$1
	 while get_pids > /dev/null; do
		 if [ $counter -gt $timeout ]; then
			 retval=2
			 break
		 fi
		 echo -n "."
		 sleep 1
		 counter=$(($counter+1))
	 done
	 echo
	 return $retval
}

#
# Function that starts the daemon/service
#
do_start()
{
	# Set Max number of file descriptors for the safety sake
	# see http://docs.fluentd.org/en/articles/before-install
	ulimit -n 65536

	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
	${START_STOP_DAEMON_ARGS} --test > /dev/null \
		|| return 1
	get_pids > /dev/null \
		&& return 2
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON \
	${START_STOP_DAEMON_ARGS} -- $DAEMON_ARGS \
		|| return 2
	# Add code here, if necessary, that waits for the process to be ready
	# to handle requests from services started subsequently which depend
	# on this one.  As a last resort, sleep for some time.
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred

	wait_to_term=300
	wait_to_kill=5

	start-stop-daemon --stop --quiet --retry=TERM/$wait_to_term/KILL/$wait_to_kill --pidfile $PIDFILE --name ruby
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2

	# Handle the case when either pid-file is missing or parent process
	# is dead but children are still running (with different PID)
	PIDs=$(get_pids)
	if [ -n "$PIDs" ]; then
		# Try to send TERM and wait
		echo "Send TERM"
		kill $PIDs
		wait_pids $wait_to_term
		RETVAL="$?"

		# Try to send KILL and wait
		if [ "$RETVAL" = 2 ]; then
			echo "Send KILL"
			kill -9 $PIDs
			wait_pids $wait_to_kill
			RETVAL="$?"
		fi
	fi

	[ "$RETVAL" = 2 ] && return 2
	rm -f $PIDFILE
	return "$RETVAL"
}

#
# Function that sends a SIGHUP to the daemon/service
#
do_reload() {
	#
	# If the daemon can reload its configuration without
	# restarting (for example, when it is sent a SIGHUP),
	# then implement that here.
	#
	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name ruby
	return 0
}

do_configtest() {
	eval "$DAEMON_ARGS --user ${USER} --group ${GROUP} --dry-run -q"
}

case "$1" in
  start)
    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC " "$NAME"
    do_start
    case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
  ;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
       status_of_proc "$DAEMON" ruby && exit 0 || exit $?
       ;;
  reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	log_daemon_msg "Reloading $DESC" "$NAME"
	do_reload
	log_end_msg $?
	;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	do_configtest || return $?
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
	  	# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  configtest)
	do_configtest
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload|configtest}" >&2
	exit 3
	;;
esac

:
