Document: td-agent
Title: Debian td-agent Manual
Author: <insert document author here>
Abstract: This manual describes what td-agent is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/td-agent/td-agent.sgml.gz

Format: postscript
Files: /usr/share/doc/td-agent/td-agent.ps.gz

Format: text
Files: /usr/share/doc/td-agent/td-agent.text.gz

Format: HTML
Index: /usr/share/doc/td-agent/html/index.html
Files: /usr/share/doc/td-agent/html/*.html
