Document: trd-agent
Title: Debian trd-agent Manual
Author: <insert document author here>
Abstract: This manual describes what trd-agent is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/trd-agent/trd-agent.sgml.gz

Format: postscript
Files: /usr/share/doc/trd-agent/trd-agent.ps.gz

Format: text
Files: /usr/share/doc/trd-agent/trd-agent.text.gz

Format: HTML
Index: /usr/share/doc/trd-agent/html/index.html
Files: /usr/share/doc/trd-agent/html/*.html
